[package]
name = "td4"
version = "0.1.0"
authors = ["tsuyoshiwada <wadackel@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
num-traits = "0.2"
num-derive = "0.2"
wasm-bindgen="0.2"
lazy_static = "1.3.0"
